server:
  port: 10001
  context-path: /uaa
  use-forward-headers: true

feign:
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
spring:
  profiles: development
  aop:
    proxy-target-class: true
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://172.16.112.96:3306/yyauth?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 6
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.112.91:8761/eureka/
  instance:
    preferIpAddress: true


foxauth:
  token:
    validity_seconds: 1000000000
    
#security:
#  basic:
 #   enabled: false
 # sessions: if_required

logging:
  level:
    org.springframework.security: DEBUG
  path: /yy/logs/yy_micro/baseplatform/

foxcloud:
  security:
    ldap_salt: a6dd4ac4-c1d1-11e6-80e4-0050568a49fd



