
server:
  port: 9101
logging:
  path: /yy/logs/yy_micro/core/
  level:
    org.springframework.security: DEBUG

feign:
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

security:
  basic:
    enabled: false
  ignored: /noauth/**, /swagger**,/swagger**/**,/webjars/**,/v2/**, /js/**, /css/**, /authsec/users/loadByLoginName, /authsec/users/loadById, /tenant/*/organization/quota
  oauth2:
    client:
      client-id: fox-service
      client-secret: secret
      access-token-uri: http://authserver:9001/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://authserver:9001/uaa/oauth/check_token


---
spring:
  profiles: cloud
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://15.114.102.7:3306/foxbase?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 0
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000


eureka:
  client:
    serviceUrl:
      defaultZone: http://pro-discovery:8761/eureka/
  instance:
    hostname: pro-usermgmt
    nonSecurePort: 80
    
---
spring:
  profiles: development
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://15.114.102.7:3306/foxbase?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 6
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000


eureka:
  client:
    serviceUrl:
      defaultZone: http://dev-discovery:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: test
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://15.114.102.7:3306/foxtest?useUnicode=true&amp;characterEncoding=utf8
    username: admin
    password: 1qaz!QAZ
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 11
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000


eureka:
  client:
    serviceUrl:
      defaultZone: http://test-discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: local
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/yy-base?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  redis:
    database: 6
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  data:
    rest:
      default-page-size: 1000

security:
  basic:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    