
server:
  port: 8761
   
logging:
  path: /yy/logs/yy_micro/baseplatform/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
    
---
spring:
  profiles: cloud
eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka/

---
spring:
  profiles: development
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    

---
spring:
  profiles: test
eureka:
  instance:
    preferIpAddress: true
  client:
    preferIpAddress: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST}:${DISCOVERY_SERVICE_PORT}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  
---
spring:
  profiles: local
eureka:
  instance:
    preferIpAddress: true
  client:
    preferIpAddress: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  
  
#spring.cloud.config.discovery.enabled: true
