apiVersion: v1
kind: ReplicationController
metadata:
  name: config
  namespace: default
spec:
  replicas: 1
  selector:
    app: config
  template:
    metadata:
      name: config
      labels:
        app: config
      namespace: default
    spec:
      containers:
        - name: config
          image: 192.168.0.32:443/lizcloud/liz-config:latest
          ports:
            - name: server-port
              containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: development
            # - name: spring_cloud_config_server_git_uri
            #   value: http://15.114.102.28/foxcloud/config.git
            # - name: spring_cloud_config_server_git_username
            #   value: foxcloud
            # - name: spring_cloud_config_server_git_password
            #   value: -TsuqKj7is8fUos5Z5FK
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dev-sec
