server:
  port: 9302
logging:
  path: /yy/logs/yy_micro/api/
#    信道维持时间
ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
          strategy: SEMAPHORE

feign:
  hystrix:
    enabled: false
proxy:
  auth:
    routes:
      basis: oauth2

security:
  basic:
    enabled: false
  ignored: /noauth/**, /swagger**,/swagger**/**,/webjars/**,/v2/**, /js/**, /css/**
  oauth2:
    client:
      client-id: fox-service
      client-secret: secret
      access-token-uri: http://${AUTHSERVER_SERVICE_HOST}:${AUTHSERVER_SERVICE_PORT}/uaa/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://${AUTHSERVER_SERVICE_HOST}:${AUTHSERVER_SERVICE_PORT}/uaa/oauth/check_token


---
spring:
  profiles: development
  redis:
    database: 6
    host: 15.114.102.10
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.112.91:8761/eureka/
  instance:
    preferIpAddress: true


